### PR TITLE
T7 f2 19 setting up firebase project

### PR DESCRIPTION
**Pull request by voonic**
Added firebase config for our project, commit contains only firebase settings.

### CODE REVIEW

**Comment by javier-rosas** [comment]
Hey Saket! This merge should be painless because the only thing you have changed is the package.json, and you have created a separate authentication directory.  

Question: Should we create a dot env file for the API key? If so, we should do that.

**Comment by voonic** [comment]
This is standard practice for firebase, the same is shown in their documentation. Also, the keys are public so I guess that's not required.

**Comment by javier-rosas** [comment]
We just need to resolve the package-json conflict and its good to go.

**Comment by javier-rosas** [comment]
No conflicts! Looks good to merge.

**Pull request merged**
